.github/workflows/android.yml
This patch adds github action to build android
=> Action: Add github action gradle build

ml_inference_offloading/src/main/AndroidManifest.xml, ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/MainService.kt
This patch removes hardcoded IP address and uses Connectivity manager to get IP address.
=> App/Service: Get IP address form device

ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/MainActivity.kt, ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/MainService.kt, ml_inference_offloading/src/main/res/layout/activity_main.xml
This patch shows tensor_query_server's port number the clinet application will use on the screen.
=> App: Show tensor_query_server's port number in activity

ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/MainActivity.kt, ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/MainService.kt
This patch makes the activity to handle model.
When a model is added, it can be accessed through an activity.
=> App: Let the activity handles model

gradle/libs.versions.toml
This patch updates tflite version in libs.versions.toml
=> Gradle: Support tflite v2.16.1

externals/build.gradle.kts
This patch revises the Gradle build script in the 'externals' directory to handle the mandatory and optional properties separately.
=> Externals/Gradle: Update the handling mechanism for the given properties

nnstreamer-api/build.gradle.kts
This patch updates the Gradle build script to support SNPE. The version of SNPE must be above 2.10.
=> API/Gradle: Add an option to enable supporting SNPE

build.gradle.kts, gradle/libs.versions.toml, ml_inference_offloading/build.gradle.kts
This patch declares to use the Room Persistence library in the App.
=> Gradle/App: Declare dependencies to use Room 

ml_inference_offloading/src/main/AndroidManifest.xml, ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/MainActivity.kt, ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/MainService.kt
This is a trivial patch that fixes broken coding conventions.
=> App: Fix broken coding conventions

nnstreamer-api/build.gradle.kts
This patch fixes a bug related to enabling TFLite support.
=> Gradle/Api: Bug-fix related to enabling TFLite support

ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/MainService.kt, ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/data/Model.kt, ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/data/ModelDao.kt, ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/data/ModelDatabase.kt, ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/data/ModelsRepository.kt, ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/data/OfflineModelsRepository.kt, ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/data/ServiceContainer.kt
This patch adds the initial implementation of a DAO for the ML Model entity.
=> App/Data: Implement a DAO for the ML Model entity 

ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/MainService.kt
This patch introduces NsdManager.
If NsdManager register service on the network,
client which connected to the same network could get IP address and port number.
=> App/Service: Introduce NsdManager to register service on the network

.github/workflows/android.yml
This patch adds step to test reports if failed.
=> Action: Upload test reports if failed

ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/MainService.kt
This patch injects a dependency on PreferencesDataStore into the MainService component.
=> App/Service: Inject a dependency on PreferencesDataStore

.github/actions/set-up/action.yml, .github/workflows/android.yml
This patch adds composite action for set up android build.
=> Action: Add android build set-up composite action

ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/data/Model.kt, ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/data/ModelDao.kt, ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/data/ModelRepository.kt, ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/data/ModelRepositoryImpl.kt
This patch adds KDoc documentation comments to the classes and interfaces of the Room database for the Model entity.
=> Data/Model: Add KDoc documentation comments to the Model ROOM DB

ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/ui/MainViewModel.kt
This patch adds KDoc documentation comments to the classes of MainViewModel.
=> ViewModel/Doc: Add KDoc documentation comments for MainViewModel

ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/data/Model.kt, ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/data/ModelDao.kt, ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/data/ModelRepository.kt, ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/data/ModelRepositoryImpl.kt, ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/data/OffloadingService.kt, ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/data/OffloadingServiceDao.kt, ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/data/OffloadingServiceRepository.kt, ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/data/OffloadingServiceRepositoryImpl.kt
This patch adds KDoc documentation to the classes and interfaces of the Room database for the OffloadingService entity.
=> Data/OffloadingService: Add KDoc for OffloadingService

.github/workflows/docs.yml
This patch adds github action to create documentation when triggered.
=> Action: Add github action to create dokka documentation

ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/network/NsdRegistrationListener.kt, ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/providers/ModelFileProvider.kt, ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/ui/components/ServiceUi.kt
This PR adds Kdoc documentation for NsdRegistrationListener and Service UI.
=> Doc: Add KDoc for network and UI

ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/data/AppDatabase.kt
This patch adds KDoc documentation comments for the AppDatabase and its helper class.
=> Data/Doc: Add KDoc documentation comments for the AppDatabase class

ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/di/AppComponent.kt, ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/di/DataStoreModule.kt, ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/di/DatabaseModule.kt
This patch adds KDoc documentation comments to the files for Dependency Injection framework.
=> DI/Doc: Add KDoc documentation comments to the file for DI

ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/MainActivity.kt, ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/MainService.kt
This patch changes to use a messenger to communicate.
Messenger makes MainService to work across different processes.
loadModels function's CoroutineScope is expanded to remove `suspend` keyword.
handleMessage in Handler class is not `suspend` function, so we can't call `suspend` function in that function.
=> Messenger: Use a Messenger to communicate

ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/MainService.kt
This patch changes some functions to private which is only used inside the MainService class.
=> Service: Change some functions to private

ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/MainService.kt
This patch adds KDoc documentation for MainService.
=> Service: Add KDoc documentation comments for MainService

README.md
This patch adds a basic draft of the README.md file.
=> README: Add a draft of README.md

gradle/libs.versions.toml, ml_inference_offloading/build.gradle.kts
This patch imports Dokka plugin name dokka-mermaid to render Mermaid graphics from code comments.
=> Gradle/Dokka: Introduce a Dokka plugin dokka-mermaid

ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/ui/theme/Color.kt, ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/ui/theme/Theme.kt, ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/ui/theme/Type.kt
This patch adds KDoc documentation comments for the Composable functions and properties in ui/theme.
=> UI/KDoc: Add KDoc documentation comments for the files in ui/theme

ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/App.kt
This patch adds app architecture using mermaid graph.
=> Doc: Add mermaid graph of app architecture

ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/ui/components/ServiceUi.kt
This patch adds KDoc documentation comments to the composable function, temporarily implemented for the test purpose.
=> UI/KDoc: Add KDoc documentation comments to a composable function

ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/MainService.kt, ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/data/Model.kt
This patch adds a method to get the filter description for the NNStreamer pipeline from the Model class.
=> Data/Model: Add a method to get NNStreamer filter description

build.gradle.kts, gradle/libs.versions.toml, ml_inference_offloading/build.gradle.kts, ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/MainActivity.kt
This patch introduces a ModalNavigationDrawer into the Main Activity to support multiple navigationable screens.
=> Activity: Introduce ModalNavigationDrawer to support multiple screens

ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/data/Model.kt
This patch supports flexible tensors in filter description.
```json
{
"single" :
{
"framework" : "custom",
"model" : ["libnnstreamer_customfilter_llama2.so"],
"input_info" : [
{
"format" : "flexible"
}
],
"output_info" : [
{
"format" : "flexible"
}
]
}
}
```
creates `other/tensors,format=flexible,framerate=0/1 ! tensor_filter framework=tensorflow-lite model=/storage/.../libnnstreamer_customfilter_llama2.so ! other/tensors,format=flexible,framerate=0/1
`
The return value of the existing conf is the same with the different order.
=> Data/Model: Support flexible tensors in filter description

ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/MainService.kt
This patch changes NSD service name to use model name.
=> NSD: Change service name to use modle name

ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/data/Model.kt
This patch removes hard-coded tensorflow-lite to supports multiple framework.
=> Data/Model: Supports multiple framework

documentation/sd_fusing_rpi3.sh
This patch updates SD fusing scripts for rpi.
=> Documentation: Update SD fusing scripts

documentation/getting_started.md
This patch adds documentation to build android application to supports llama2c.
=> Documentation: Add docs to build with llama2c

ml_inference_offloading/src/main/AndroidManifest.xml, ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/MainActivity.kt
Changed to ask notification permission.
=> Ask notification permission to user
