- gradle/libs.versions.toml
- nnstreamer-api/Android.mk
- nnstreamer-api/Application.mk
- nnstreamer-api/build.gradle.kts
- settings.gradle.kts
This patch configures a Gradle subproject, nnstreamer-api, that generates an AAR file to provide the NNStreamer Android API.
For the test purpose, only the universal GStreamer library for Android is currently included in the AAR file instead of the NNStreamer library.
> Gradle/NNSApi: Configure nnstreamer-api, a Gradle subproject

- .gitmodules
Currently, ML API requires nnstreamer-edge to build the Java API by default. For this reason, this patch adds nnstreamer-edge as a git submodule.
> Git: Add nnstreamer-edge as a git submodule

- ml_inference_offloading/src/main/AndroidManifest.xml
- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/MainActivity.kt
- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/MainService.kt
This patch adds an empty service that runs in the foreground to the ML Inference Offloading App. The Service is launched by the
startForegroundService method in the onCreate callback of the Activity.
> App/Service: Implement an empty foreground service

- gradle.properties
Gradle build is occasionally failed by "java.lang.OutOfMemoryError: Java heap space". This patch adds a workaround to avoid this error.
> Gradle: Add a workaround for java.lang.OutOfMemoryError

- ml_inference_offloading/build.gradle.kts
This patch revises the plugin dependencies of the App to use plugin IDs instead of the alias, which includes specific version numbers. The multiple uses of the alias are likely to incur the following error:
The request for this plugin could not be satisfied because the plugin is already on the classpath with an unknown version, so compatibility cannot be checked.
> App/Gradle: Revise plugin dependencies to avoid build error

- build.gradle.kts
This patch adds buildscript dependencies to fix build error in externals.
> Gradle: Fix build error in externals

- .github/workflows/android.yml
- externals/build.gradle.kts
This PR removes copied gstreamer tar file in external/build.gradle.kts
Remained tar file causes no space left error. (2.6G gstreamer-1.0-android-universal-1.24.0.tar)
Also, gradle-build-action is deprecated.
> Fix no space left on device error in github action.

- ml_inference_offloading/build.gradle.kts
- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/MainService.kt
- nnstreamer-api/build.gradle.kts
This patch adds nnstreamer to android service.
> App/Service: Add nnstreamer to ml_inference_offloading service

- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/MainActivity.kt
- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/MainService.kt
- ml_inference_offloading/src/main/res/layout/activity_main.xml
This patch bounds service to MainActivity.
Reference: https://developer.android.com/develop/background-work/services/bound-services
> App/Service: Bound service to MainActivity 

- .gitignore
- externals/build.gradle.kts
- gradle.properties
- gradle/libs.versions.toml
- nnstreamer-api/build.gradle.kts
This patch adds tflite option in external gradle.
If gradle.properties file has `dir.tfliteAndroid` value, tflite library will be downloaded to externals repo.
needs : https://github.com/nnstreamer/api/pull/499
> Gradle/Externals: Add tflite option

- .github/workflows/android.yml
- externals/build.gradle.kts
This patch removes unused package in runner to free up more space.
Reference : https://github.com/apache/flink/blob/master/tools/azure-pipelines/free_disk_space.sh#L28-L53
> Action: Remove unused package to free up more space

- ml_inference_offloading/src/main/AndroidManifest.xml
- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/MainService.kt
This patch implements tensor query server related functions.
HOST_ADDR is now for internal network only.
> App/Service: Use tensor query server in service

- externals/build.gradle.kts
- nnstreamer-api/build.gradle.kts
This patch modifies build.gradle.kts in the externals submodule to use the existing gradle tasks to download and extract archive files.
> Externals/Gradle: Revise build.gradle.kts

- externals/build.gradle.kts
This patch adds a Gradle task that cleans all of the generated directories and files.
> Externals/Gradle: Add a Gradle task for cleaning all of the generated 

- nnstreamer-api/build.gradle.kts
Instead of src/main/java/$NAMESPACE/java, src/main/java/$NAMESPACE is the right location for the NNS API Java source code generation. This patch reverts such change to the right one.
> Api/Gradle: Revert the location for NNS Java source code generation

- nnstreamer-api/build.gradle.kts
This patch is aimed at refactoring the code related to actions in AfterEvaluate.
> Api/Gradle: Clean code for actions in AfterEvaluate

- externals/build.gradle.kts
This patch removes unnecessary code snippets in the Gradle build script of the externals module.
> Externals/Gradle: Remove unnecessary code snippets

- externals/build.gradle.kts
This PR includes the following commits to update several trivial things in externals/build.gradle.kts.
- Externals/Gradle: Apply plugins using the modern way
- Externals/Gradle: Use dir.tfliteAndroid as an option to enable TFLite
> Externals/Gradle: Update trivial things

- gradle.properties
- nnstreamer-api/build.gradle.kts
This patch replaces several hard-coded path strings with the values from the gradle.properties file.
> Api/Gradle: Eliminate hard-coded path strings

- build.gradle.kts
This patch adds a Gradle task that recursively triggers the cleanAll tasks to the build.gradle.kts file in the project root directory.
> Gradle: Add a Gradle task that triggers cleanAll recursively

- .github/workflows/android.yml
This patch adds step to upload ml_inference_offloading apk, and cron schedule to github action.
> Action: Daily build and upload apk

- ml_inference_offloading/src/main/AndroidManifest.xml
- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/App.kt
- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/MainService.kt
This patch revises the getIpAddress method to return the proper localhost address corresponding to the emulator or the real target. Moreover, the platform-type variables are eliminated.
> App/Service: Revise the getIpAddress method

- externals/build.gradle.kts
To make git submodules track the remote branch, this patch updates the Gradle build script of the subproject, "externals".
> Externals/Gradle: Make git submodules track the remote branch

- externals/build.gradle.kts
This patch adds an integrity verification mechanism for the files downloaded from an external link.
> Externals/Gradle: Add integrity verification mechanism for downloadables

- ml_inference_offloading/build.gradle.kts
- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/MainActivity.kt
- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/MainService.kt
- ml_inference_offloading/src/main/res/layout/activity_main.xml
- ml_inference_offloading/src/main/res/layout/models.xml
This patch replaces buttons and textView to ListView for supporting various model.
Also, MainService's class variable tensorQueryServer is replaced to MutableMap.
> App: Use RecyclerView and map to support various model

- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/MainActivity.kt
This patch changes Java to Kotlin libraries.
Privious code is created with android-studio's Convert Java to Kotlin.
Related to : https://github.com/nnstreamer/nnstreamer-android/pull/36#discussion_r1634983627
> App/Activity: Change file related Java libraries to Kotlin

- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/MainActivity.kt
- ml_inference_offloading/src/main/res/layout/models.xml
This patch adds yolov8 ml offloading.
Tensor query client has to decode the result which server sends.
> App: Support Yolov8 model 

- externals/build.gradle.kts
This fixes a bug in the Gradle task named 'cleanAll' by reordering the sequence of task execution.
> Externals/Gradle: Reorder the sequence of task execution

- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/MainActivity.kt
- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/MainService.kt
- ml_inference_offloading/src/main/res/layout/models.xml
- ml_inference_offloading/src/main/res/values/strings.xml
This patch seperates pipeline pause and close.
Also, now we can see pipeline status in main activity.
This PR needs https://github.com/nnstreamer/nnstreamer/pull/4488
> App: Seperate pipeline pause and close

- gradle.properties
- gradle/libs.versions.toml
- ml_inference_offloading/build.gradle.kts
This PR revises some configurations of the build scripts and environments before introducing the Room Persistence library to the project as follows:
- Gradle/App: Revise Project.dependencies for the App
- Gradle/App: Update the target JVM to 17
- Gradle: Declare code style for kotlin
> Gradle/App: Update the target JVM to 17 

- ml_inference_offloading/src/main/AndroidManifest.xml
- ml_inference_offloading/src/main/res/xml/file_paths.xml
This patch introduces an Android component, FileProvider (a subclass of ContentProvider), that serves ML model files to other components.
> App/FileProvider: Introduce FileProvider for serving ML model files 

- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/MainActivity.kt
This patch changes tensor format from other/tensor to other/tensors.
other/tensor is obsoleted.
> App/Activity: Use other/tensors in mobileNet filter

- ml_inference_offloading/src/main/AndroidManifest.xml
- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/MainActivity.kt
- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/providers/ModelFileProvider.kt
- ml_inference_offloading/src/test/java/ai/nnstreamer/ml/inference/offloading/ActivityUnitTest.kt
This patch makes the ModelFileProvider pre-load the model files, which are packaged into the APK file. According to this change, a test case for verifying the number of models preloaded has also been updated.
> App/Activity: Let the FileProvider load bundled model files

- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/MainActivity.kt
This patch changes tensor format from other/tensor to other/tensors. other/tensor is obsoleted.
> App/Activity: Use other/tensors in private external models

- .github/workflows/android.yml
This patch fixes github action failed fetch to apt-mirrors.
https://github.com/actions/runner-images/issues/10221#issuecomment-2225978317
> Action: Fix broken CI

- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/providers/ModelFileProvider.kt
This PR improves the ModelFileProvider;
- to copy model files bundled in the App package using a separate thread 
- copy the model files only if the targets do not exist
> Providers/ModelFile: Copy model files using a separate thread 

- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/data/OffloadingService.kt
This patch adds index on OffloadingService's foreigh key.
If we do not use it, it may trigger full table scans whenever parent table is modified.
resolves : #64
> App/Data: Use index on foreign key

- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/MainService.kt
This patch makes service to close all the pipelines when `onDestroyed`.
The pipelines could not work properly when the service is destroyed.
So it is necessary to explicitly close them and remove if from the database.
Related to : #63
> App/Service: Close all the pipelines when service is destroyed

- gradle/libs.versions.toml
- ml_inference_offloading/build.gradle.kts
- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/data/PreferencesDataStore.kt
- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/data/PreferencesDataStoreImpl.kt
- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/di/AppComponent.kt
- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/di/DataStoreModule.kt
While the ROOM library supports saving relatively large and complex data, the DataStore, which is replacing SharedPreferences, aims at saving small and light data. This patch introduces Preferences DataStore to track and maintain the App's status in the App-Wide scope.
> App/Data: Introduce Preferences DataStore

- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/MainService.kt
In the MainService, a created service requires a unique identifier. To this end, gServiceId, a private class integer member, has been used. However, a class member would be invalidated or reinitialized after the instance is destroyed, so a more durable solution to generate an identifier number is needed· For this reason, this patch replaces gServiceId with DataStore's incrementalCounter.
> App/Service: Replace gServiceId with DataStore's increamentalCounter 

- build.gradle.kts
- gradle/libs.versions.toml
- ml_inference_offloading/build.gradle.kts
- nnstreamer-api/build.gradle.kts
This patch imports Dokka, an API documentation engine that supports automatic documentation generation.
```bash
./gradlew dokkaHtml
```
See Also: [dokka-plugins](https://kotlinlang.org/docs/dokka-plugins.html), [Module documentation](https://kotlinlang.org/docs/dokka-module-and-package-docs.html)
> Gradle/Doc: Introduce an API documentation engine, Dokka

- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/providers/ModelFileProvider.kt
This is a trivial patch to replace the misused method takeWhile with filter. Note that takeWhile returns the first element of the list that satisfies the given condition.
> Providers/ModelFile: Replace misused takeWhile with filter

- gradle/libs.versions.toml
- ml_inference_offloading/build.gradle.kts
- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/data/AppDatabase.kt
- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/data/Model.kt
This PR updates the Model entity to support the Tizen ML model config file of the 'single' type. In detail, the Model entity includes Map<String, String> and Map<String, List<String> typed data so that a TypeConvert class that supports type conversion from those types to JSON strings is also added.
> App/Data: Update the Model entity

- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/providers/ModelFileProvider.kt
This patch adds the KDoc documentation comments to ModelFileProvider.
> App/Doc: Add KDoc documentation comments for ModelFileProvider

- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/providers/ModelFileProvider.kt
This patch updates the ModelFileProvider component to parse model config files when it copies model files in the assets directory to the App's private external storage.
> Provider/Model: Support parsing model config files

- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/data/Model.kt
This patch updates the parsing code for the model configuration file to support specifying the model file using a single string instead of a JSON Array.
> Provider/Model: Handle the case when a single model is given

- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/MainActivity.kt
- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/MainService.kt
- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/ui/components/ServiceUi.kt
This patch updates MainService and MainActivity to use pre-loaded model files by ModelFileProvider. These are temporary changes before revising ModelRepository APIs.
> App/Service: Update MainService to use pre-loaded model files 

- build.gradle.kts
- ml_inference_offloading/build.gradle.kts
This patch adds configurations for the options in DokkaTasks to the Gradle build script to allow customization of the documentation outputs.
> App/Gradle: Configure DokkaTasks' options for customization

- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/data/PreferencesDataStore.kt
- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/data/PreferencesDataStoreImpl.kt
This patch adds KDoc documentation comments for the PreferencesDataStore and PreferencesDataStoreImpl classes.
> Data/KDoc: Add KDoc documentation comments for PreferencesDataStore

- .github/workflows/docs.yml
This patch updates the existing GitHub Actions workflow, which generates KDoc to build and deploy documentation using Jekyll and GitHub Pages. The KDoc HTML pages are moved to /KDoc under the GitHub Pages.
> GitHub/Actions: Update the workflow script for gh-pages w/ KDoc

- README.md
This patch adds the KDoc badge and hyperlink that points to the page automatically generated by a GitHub Actions workflow to the README.md file.
> README: Add KDoc badge and link to the READMD.md file

- externals/build.gradle.kts
- gradle.properties
- nnstreamer-api/build.gradle.kts
This patch updates the Gradle build script to support TensorFilter sub-plugin for llama2.c.
> API/Gradle: Add an option to enable supporting llama2.c

- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/data/Model.kt
This patch fixes wrong format type when get tensors.
> Data/Model: Fix wrong format type

- gradle/libs.versions.toml
- ml_inference_offloading/build.gradle.kts
- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/MainActivity.kt
- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/MainService.kt
This PR removes unnecessary code in MainService to fix bugs related to loading models whenever the service is created. In addition, this changes the method for collecting the StateFlow of the OffloadingServiceUiStates to the one that is lifecycle-aware.
> App: Fix bugs related to loading models whenever the service is created

- ml_inference_offloading/src/main/assets/models/README.md
- ml_inference_offloading/src/main/assets/models/llama2c.conf
This patch adds llama2c configuration file.
model and tokenizer bin file have to be copied to assets directory to use llama2 conf.
> Assets/Modles: Add llama2c configuration file

- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/MainService.kt
- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/network/Util.kt
This patch extracts network realted util functions from MainService.
> Network/Util: Extract network util functions from MainService

- ml_inference_offloading/src/main/assets/models/imagenet_labels.txt
- ml_inference_offloading/src/main/assets/models/mobilenet_v1_1.0_224_quant.conf
This patch adds a text file that contains the ImageNet labels which are commonly used in object classification models.
> Assets/Label: Add a text file that contains the ImageNet labels 

- gradle/libs.versions.toml
- ml_inference_offloading/build.gradle.kts
- ml_inference_offloading/src/main/AndroidManifest.xml
- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/MainActivity.kt
- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/MainService.kt
- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/data/Classification.kt
- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/data/ImageAnalyzer.kt
- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/domain/MobilenetClassifier.kt
- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/domain/ObjectClassifier.kt
- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/ui/MainViewModel.kt
This patch adds a draft of the vision example (i.e., an object classification scenario using MobileNet_v1) that exploits the MLAgent
Service.
> App/Vision: Add a vision example that the exploits MLAgent Service

- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/MainService.kt
- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/domain/LlamaUtil.kt
- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/domain/NewDataCb.kt
This patch adds a draft of the LLM example.
It uses llama2 model to generate text using input prompt.
> App/Language: Add a LLM example about text generation

- documentation/example_conf/llama2c.conf
- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/data/Model.kt
Data/Model: Support invoke-dynamic option
This patch supports invoke-dynamic option at tensor_filter.
If output tensor format is flexible, invoke-dynamic has to be set TRUE.
Conf: Change llama2 output to flexbile
This patch changes llama2 configuration file.
Output flexbile is now supported, so changed it from uint8 static to flexible.
> Data/Model: Support invoke-dynamic option

- ml_inference_offloading/src/main/java/ai/nnstreamer/ml/inference/offloading/data/ImageAnalyzer.kt
This patch updates the ImageAnalyzer class, which is an abstraction layer of the concrete image analysis implementation, to support condition-based frame-skipping.
> App/Vision: Update the ImageAnalyzer class to support frame-skipping

- ml_inference_offloading/build.gradle.kts
This patch fixes the following warning to reduce the APK's file size.
"Unable to strip the following libraries, packaging them as they are:
libandroidx.graphics.path.so,
libc++_shared.so,
libdatastore_shared_counter.so,
libgstreamer_android.so,
libimage_processing_util_jni.so,
libnnstreamer-native.so,
libtensorflowlite.so,
libtensorflowlite_gpu_delegate.so."
This size of `./ml_inference_offloading/build/outputs/apk/release/ml_inference_offloading-release-unsigned.apk ` comparisons
|   | Before | After |
|---|---|---|
| Size  |  1.1GiB | 289MiB   |
> Gradle/Android: Fix the warning related to unable to strip native libs

- build.gradle.kts
- ml_inference_offloading/build.gradle.kts
This patch resolves the bug in the 'cleanAll' gradle task, which now also cleans the omitted sub-project.
> Gradle/Android: Fix the gradle task that cleans the entire project

- gradle.properties
- nnstreamer-api/build.gradle.kts
This patch adds an option to supporting llamacpp
> Gradle/Android: Add an option to enable supporting llamacpp
